### ISSUE TITLE
vkcube hangs with runtime layer enabled on ubuntu 22.04

### ISSUE THREAD

**Issue by kuhar** [googlestadia/performance-layers#71]
This is under docker & lavapipe.
The other layers don't hang vkcube.

**Comment by kuhar** [comment]
Running a debug build shows an assertion failure:
```
root@61641fa5d3ce:/build# timeout 5s /performance-layers/docker/test_performance_layers.sh .
Selected GPU 0: llvmpipe (LLVM 13.0.1, 256 bits), type: Cpu
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
vkcube: /performance-layers/layer/layer_data.h:237: auto performancelayers::LayerData::GetNextDeviceProcAddr(DispatchableDeviceHandleT, TFuncPtr) const [DeviceHandleT = VkCommandBuffer_T *, TFuncPtr = VkResult (*VkLayerDispatchTable_::*)(VkDevice_T *, VkQueryPool_T *, unsigned int, unsigned int, unsigned lounsigned long, unsigned int)]: Assertion `device_dispatch_iter != device_dispatch_map_.end()' failed.
```

**Comment by kuhar** [comment]
Stack trace:

```
#5  0x00007fa1f260071b in __assert_fail_base (fmt=0x7fa1f27b5150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x7fa1e8a738f6 "device_dispatch_iter != device_dispatch_map_.end()", file=0x7fa1e8a74e4b "/performance-layers/layer/layer_data.h",     line=242, function=<optimized out>) at ./assert/assert.c:92
#6  0x00007fa1f2611e96 in __GI___assert_fail (assertion=0x7fa1e8a738f6 "device_dispatch_iter != device_dispatch_map_.end()", 
    file=0x7fa1e8a74e4b "/performance-layers/layer/layer_data.h", line=242, 
    function=0x7fa1e8a6a505 "auto performancelayers::LayerData::GetNextDeviceProcAddr(DispatchableDeviceHandleT, TFuncPtr) const [DispatchableDeviceHandledBuffer_T *, TFuncPtr = VkResult (*VkLayerDispatchTable_::*)(Vk"...) at ./assert/assert.c:101#7  0x00007fa1e8addffa in performancelayers::LayerData::GetNextDeviceProcAddr<VkCommandBuffer_T*, VkResult (* VkLayerDispatchTable_::*)(VkDevice_T*, VkQuensigned int, unsigned int, unsigned long, void*, unsigned long, unsigned int)> (    this=0x7fa1e8bda7f0 <(anonymous namespace)::GetLayerData()::layer_data>, device_handle=0x55591ca5bfa0,     func_ptr=&VkLayerDispatchTable_::GetQueryPoolResults) at /performance-layers/layer/layer_data.h:242
#8  0x00007fa1e8add268 in performancelayers::RuntimeLayerData::LogAndRemoveQueryPools (    this=0x7fa1e8bda7f0 <(anonymous namespace)::GetLayerData()::layer_data>) at /performance-layers/layer/runtime_layer_data.cc:68
#9  0x00007fa1e8acaeb1 in (anonymous namespace)::RuntimeLayer_DeviceWaitIdle (device=0x55591cb3fa50) at /performance-layers/layer/runtime_layer.cc:313
#10 0x000055591b004c6c in ?? ()
#11 0x00007fa1f2601d90 in __libc_start_call_main (main=main@entry=0x55591b002cb0, argc=argc@entry=3, argv=argv@entry=0x7ffcf7ef6228)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#12 0x00007fa1f2601e40 in __libc_start_main_impl (main=0x55591b002cb0, argc=3, argv=0x7ffcf7ef6228, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffcf7ef6218) at ../csu/libc-start.c:392
#13 0x000055591b005c0a in ?? ()
```
